var links = document.querySelectorAll('div.item-tag > a')
links.forEach((a) => { console.log(a.innerText) })

[
    { "_name": ".NET" },
    { "_name": ".NET Compact Framework" },
    { "_name": ".NET Framework" },
    { "_name": ".NET Remoting" },
    { "_name": "1ShoppingCart" },
    { "_name": "2D Animation" },
    { "_name": "2D Design" },
    { "_name": "3D Animation" },
    { "_name": "3D Rigging" },
    { "_name": "A2Billing" },
    { "_name": "ACDSee" },
    { "_name": "ADK" },
    { "_name": "ADO.NET" },
    { "_name": "ADO.NET Entity Framework" },
    { "_name": "AGAL" },
    { "_name": "AJAX" },
    { "_name": "AMQP" },
    { "_name": "ANSI C" },
    { "_name": "API" },
    { "_name": "API Development" },
    { "_name": "API Documentation" },
    { "_name": "APIs" },
    { "_name": "ARM" },
    { "_name": "ASP" },
    { "_name": "ASP.NET" },
    { "_name": "ASP.NET MVC" },
    { "_name": "ATL" },
    { "_name": "ATM Implementation" },
    { "_name": "AbleCommerce" },
    { "_name": "Ableton Live" },
    { "_name": "Abstract Window Toolkit (AWT)" },
    { "_name": "Account Management" },
    { "_name": "Account Manager" },
    { "_name": "Accounting" },
    { "_name": "Accounts Payable" },
    { "_name": "Acquisitions" },
    { "_name": "Acrylic Painting" },
    { "_name": "Actian" },
    { "_name": "ActionScript" },
    { "_name": "ActionScript 3" },
    { "_name": "Active Directory" },
    { "_name": "ActiveX" },
    { "_name": "ActiveX Data Objects (ADO)" },
    { "_name": "Ada" },
    { "_name": "Adaptive Algorithms" },
    { "_name": "Administrative Assistant" },
    { "_name": "Adobe" },
    { "_name": "Adobe AIR" },
    { "_name": "Adobe Acrobat" },
    { "_name": "Adobe After Effects" },
    { "_name": "Adobe Audition" },
    { "_name": "Adobe Captivate" },
    { "_name": "Adobe Contribute" },
    { "_name": "Adobe Creative Suite" },
    { "_name": "Adobe Director" },
    { "_name": "Adobe Dreamweaver" },
    { "_name": "Adobe Encore" },
    { "_name": "Adobe Fireworks" },
    { "_name": "Adobe Flash" },
    { "_name": "Adobe Flex" },
    { "_name": "Adobe FreeHand" },
    { "_name": "Adobe GoLive" },
    { "_name": "Adobe Illustrator" },
    { "_name": "Adobe Imageready" },
    { "_name": "Adobe InDesign" },
    { "_name": "Adobe Indesign" },
    { "_name": "Adobe Insight" },
    { "_name": "Adobe LiveCycle Designer" },
    { "_name": "Adobe Muse" },
    { "_name": "Adobe PageMaker" },
    { "_name": "Adobe Photoshop" },
    { "_name": "Adobe Photoshop Lightroom" },
    { "_name": "Adobe Premiere" },
    { "_name": "Adobe Premiere Elements" },
    { "_name": "Adobe Premiere Pro" },
    { "_name": "Adobe Soundbooth" },
    { "_name": "Adobe Wallaby" },
    { "_name": "Adobe eLearning Suite" },
    { "_name": "Advanced Business Application Programming (ABAP)" },
    { "_name": "Advertising" },
    { "_name": "Agile" },
    { "_name": "Agile Project Management" },
    { "_name": "Agile Software Development" },
    { "_name": "Agile methodology" },
    { "_name": "Akka" },
    { "_name": "Album Cover Design" },
    { "_name": "Alfresco Development" },
    { "_name": "Alfresco User" },
    { "_name": "Algorithm Development" },
    { "_name": "Algorithms & Data Structures" },
    { "_name": "Alibre Design" },
    { "_name": "Alpha" },
    { "_name": "Amazon Appstore" },
    { "_name": "Amazon EC2" },
    { "_name": "Amazon MWS" },
    { "_name": "Amazon Relational Database Service" },
    { "_name": "Amazon S3" },
    { "_name": "Amazon Web Services" },
    { "_name": "Analytical skills" },
    { "_name": "Analytics & Reporting" },
    { "_name": "Android" },
    { "_name": "Android App Development" },
    { "_name": "Android SDK" },
    { "_name": "Angular.js" },
    { "_name": "Animation" },
    { "_name": "Anime Studio" },
    { "_name": "Ansys" },
    { "_name": "Ant" },
    { "_name": "Apache" },
    { "_name": "Apache Administration" },
    { "_name": "Apache Ant" },
    { "_name": "Apache Avro" },
    { "_name": "Apache CXF" },
    { "_name": "Apache Camel" },
    { "_name": "Apache Cassandra" },
    { "_name": "Apache Click" },
    { "_name": "Apache Cocoon" },
    { "_name": "Apache Cordova" },
    { "_name": "Apache Flume" },
    { "_name": "Apache Hadoop" },
    { "_name": "Apache Hive" },
    { "_name": "Apache Jakarta POI" },
    { "_name": "Apache Kafka" },
    { "_name": "Apache Mahout" },
    { "_name": "Apache Maven" },
    { "_name": "Apache OFBiz" },
    { "_name": "Apache Shirol" },
    { "_name": "Apache Solr" },
    { "_name": "Apache Spark" },
    { "_name": "Apache Struts" },
    { "_name": "Apache Subversion (SVN)" },
    { "_name": "Apache Thrift" },
    { "_name": "Apache Tiles" },
    { "_name": "Apache Tomcat" },
    { "_name": "Apollo" },
    { "_name": "App Store" },
    { "_name": "App Usability Analysis" },
    { "_name": "AppFuse" },
    { "_name": "Appcelerator Titanium" },
    { "_name": "Appian BPM Suite" },
    { "_name": "Apple" },
    { "_name": "Apple Motion" },
    { "_name": "Apple UIKit Framework" },
    { "_name": "Apple WebObjects" },
    { "_name": "Apple Xcode" },
    { "_name": "Apple iBooks" },
    { "_name": "Apple iWeb" },
    { "_name": "Apple iWork" },
    { "_name": "AppleScript" },
    { "_name": "Application Development" },
    { "_name": "Application Lifecycle Management" },
    { "_name": "Application Programming" },
    { "_name": "Application Server" },
    { "_name": "Arabic Language" },
    { "_name": "ArcGIS" },
    { "_name": "ArcScene" },
    { "_name": "Architect" },
    { "_name": "Arduino" },
    { "_name": "Art Direction" },
    { "_name": "ArtRage" },
    { "_name": "Articulate" },
    { "_name": "Articulate Engage" },
    { "_name": "Articulate Presenter" },
    { "_name": "Articulate Storyline" },
    { "_name": "Articulate Studio" },
    { "_name": "Artificial Intelligence" },
    { "_name": "Artificial Neural Networks" },
    { "_name": "ArtiosCAD" },
    { "_name": "Artisteer" },
    { "_name": "Artlantis Studio" },
    { "_name": "Arts & Crafts" },
    { "_name": "AspDotNetStorefront" },
    { "_name": "Assembla" },
    { "_name": "Assembly Language" },
    { "_name": "Asset Management" },
    { "_name": "Asynchronous I/O" },
    { "_name": "Atlassian Confluence" },
    { "_name": "Atlassian JIRA" },
    { "_name": "Atmel AVR" },
    { "_name": "Atom" },
    { "_name": "Attention to Detail" },
    { "_name": "Auctiva" },
    { "_name": "Audacity" },
    { "_name": "Audio Design" },
    { "_name": "Audio Editing" },
    { "_name": "Audio Engineering" },
    { "_name": "Audio Mastering" },
    { "_name": "Audio Mixing" },
    { "_name": "Audio Post Production" },
    { "_name": "Audio Postediting" },
    { "_name": "Audio Production" },
    { "_name": "Audio Restoration" },
    { "_name": "Audit" },
    { "_name": "Augmented Reality" },
    { "_name": "Authorize.Net Development" },
    { "_name": "AutoHotKey" },
    { "_name": "Autocad" },
    { "_name": "Autodesk Autocad" },
    { "_name": "Autodesk Softimage" },
    { "_name": "Autodys AcceliCAD" },
    { "_name": "Autoit" },
    { "_name": "Automated Testing" },
    { "_name": "Automation" },
    { "_name": "Automotive" },
    { "_name": "Aviation" },
    { "_name": "Avid" },
    { "_name": "Avid Pro Tools" },
    { "_name": "Away3D" },
    { "_name": "Awk" },
    { "_name": "Axapta" },
    { "_name": "Axiis" },
    { "_name": "Axiom MicroStation Productivity Toolkit" },
    { "_name": "Axiom Productivity Tools" },
    { "_name": "Axure RP" },
    { "_name": "BGL Simple Fund" },
    { "_name": "BIRT" },
    { "_name": "BPCS" },
    { "_name": "Backbone.js" },
    { "_name": "Backend Development" },
    { "_name": "Bada" },
    { "_name": "Balsamiq" },
    { "_name": "Banner Ad Design" },
    { "_name": "Banner Ads" },
    { "_name": "Basecamp" },
    { "_name": "Bash" },
    { "_name": "Bash Shell Scripting" },
    { "_name": "BeOS" },
    { "_name": "Behavior Driven Development (BDD)" },
    { "_name": "Bengali" },
    { "_name": "Big Data" },
    { "_name": "BigCommerce" },
    { "_name": "Bilingual" },
    { "_name": "Billing" },
    { "_name": "BitRock Installbuilder" },
    { "_name": "Bitcoin" },
    { "_name": "Bitrix" },
    { "_name": "Bitrix Intranet" },
    { "_name": "BizTalk Server" },
    { "_name": "Black Box Testing" },
    { "_name": "BlackBerry App Development" },
    { "_name": "BlackBerry JDE" },
    { "_name": "BlazeDS" },
    { "_name": "Blitz BASIC" },
    { "_name": "Blogging" },
    { "_name": "Bloomberg" },
    { "_name": "Bluetooth" },
    { "_name": "Book Cover Design" },
    { "_name": "BoonEx Dolphin" },
    { "_name": "Boost" },
    { "_name": "Bootstrap" },
    { "_name": "Borland C++ Builder" },
    { "_name": "Borland SilkTest" },
    { "_name": "Box.net Development" },
    { "_name": "Box2D" },
    { "_name": "Brand Consulting" },
    { "_name": "Brand Management" },
    { "_name": "Branding" },
    { "_name": "Brochure Design" },
    { "_name": "BuddyPress" },
    { "_name": "Budgeting" },
    { "_name": "Bugzilla" },
    { "_name": "Business Activity Monitoring" },
    { "_name": "Business Analysis" },
    { "_name": "Business Analyst" },
    { "_name": "Business Card Design" },
    { "_name": "Business Development" },
    { "_name": "Business IT Alignment" },
    { "_name": "Business Intelligence" },
    { "_name": "Business Management" },
    { "_name": "Business Operations" },
    { "_name": "Business Plan" },
    { "_name": "Business Planning" },
    { "_name": "Business Process Modeling" },
    { "_name": "Business Process Reengineering" },
    { "_name": "Business Requirement gathering" },
    { "_name": "Business Strategies" },
    { "_name": "Business Strategy" },
    { "_name": "Buying" },
    { "_name": "C" },
    { "_name": "C#" },
    { "_name": "C++" },
    { "_name": "CG Artwork" },
    { "_name": "CGI" },
    { "_name": "CMS" },
    { "_name": "CMS Development" },
    { "_name": "CNC Programming" },
    { "_name": "COBOL" },
    { "_name": "CORBA" },
    { "_name": "CPanel" },
    { "_name": "CRM" },
    { "_name": "CS-Cart" },
    { "_name": "CSS" },
    { "_name": "CSS3" },
    { "_name": "CUDA" },
    { "_name": "CURL" },
    { "_name": "CVS" },
    { "_name": "Cache Management" },
    { "_name": "Cadence Platform" },
    { "_name": "Cairngorm" },
    { "_name": "CakePHP" },
    { "_name": "Cakewalk Sonar" },
    { "_name": "Calculus" },
    { "_name": "Call Center" },
    { "_name": "Calligraphy" },
    { "_name": "Camtasia" },
    { "_name": "Capistrano" },
    { "_name": "Capture NX2" },
    { "_name": "Carbide.c++" },
    { "_name": "Caricature Drawing" },
    { "_name": "Cartography & Maps" },
    { "_name": "Cartooning" },
    { "_name": "Caspio Administration" },
    { "_name": "Caspio Programming" },
    { "_name": "Central Desktop Development" },
    { "_name": "Centreon" },
    { "_name": "Certified Information Systems Security Professional (CISSP)" },
    { "_name": "Cfo" },
    { "_name": "Change Management" },
    { "_name": "Character Design" },
    { "_name": "Chemistry" },
    { "_name": "Chroma Key" },
    { "_name": "Chrome Extension" },
    { "_name": "Chrome OS" },
    { "_name": "Cinematography" },
    { "_name": "Cisco" },
    { "_name": "Citrix" },
    { "_name": "CiviCRM" },
    { "_name": "ClearQuest" },
    { "_name": "ClickBank" },
    { "_name": "Clipping Path" },
    { "_name": "Clojure" },
    { "_name": "Cloud Computing" },
    { "_name": "Cloud Security Framework" },
    { "_name": "CloudForge" },
    { "_name": "Clustering" },
    { "_name": "CoDeSys" },
    { "_name": "Coaching" },
    { "_name": "Cocoa" },
    { "_name": "Cocoa Touch" },
    { "_name": "Cocos2d" },
    { "_name": "Code Refactoring" },
    { "_name": "CodeIgniter" },
    { "_name": "CodeWarrior" },
    { "_name": "Codeigniter" },
    { "_name": "Coding" },
    { "_name": "CoffeeScript" },
    { "_name": "Coffeescript" },
    { "_name": "Cognos" },
    { "_name": "Cold Calling" },
    { "_name": "ColdFusion" },
    { "_name": "CollabNet TeamForge" },
    { "_name": "Collaborative Filtering" },
    { "_name": "Comet" },
    { "_name": "Comic Art" },
    { "_name": "Communication Skills" },
    { "_name": "Communications" },
    { "_name": "Compensation and Benefits" },
    { "_name": "Competitive Analysis" },
    { "_name": "Compiler" },
    { "_name": "Compliance" },
    { "_name": "Component Object Model (Microsoft COM)" },
    { "_name": "Compositing" },
    { "_name": "Computational Linguistics" },
    { "_name": "Computer Engineering" },
    { "_name": "Computer Graphics" },
    { "_name": "Computer Hardware Design" },
    { "_name": "Computer Vision" },
    { "_name": "Concept Artistry" },
    { "_name": "Concept Design" },
    { "_name": "Concept Software InPage" },
    { "_name": "ConceptShare Development" },
    { "_name": "Concrete5 CMS" },
    { "_name": "Confluence" },
    { "_name": "Constant Contact" },
    { "_name": "Construction" },
    { "_name": "Consultative Sales" },
    { "_name": "Consulting" },
    { "_name": "Consumer Products" },
    { "_name": "Contao CMS" },
    { "_name": "Content Creation" },
    { "_name": "Content Management" },
    { "_name": "Content Marketing" },
    { "_name": "Content Strategy" },
    { "_name": "Continuous Integration" },
    { "_name": "Control Systems" },
    { "_name": "Copy Writing and Editing" },
    { "_name": "Copywriting" },
    { "_name": "Core Java" },
    { "_name": "Corel Paint Shop Pro" },
    { "_name": "Corel Painter" },
    { "_name": "Corel Ventura" },
    { "_name": "CorelDRAW" },
    { "_name": "Corona" },
    { "_name": "Corporate Brand Identity" },
    { "_name": "Cosmos OS" },
    { "_name": "Cover Design" },
    { "_name": "Covers & Packaging" },
    { "_name": "Creative & Talent" },
    { "_name": "Creative Direction" },
    { "_name": "Creative Problem Solving" },
    { "_name": "Creative Writing" },
    { "_name": "Cross-Functional Team Leadership" },
    { "_name": "Cryptography" },
    { "_name": "Crystal Reports" },
    { "_name": "Cubecart" },
    { "_name": "Cucumber" },
    { "_name": "Custom CMS" },
    { "_name": "Customer Information Control System (CICS)" },
    { "_name": "Customer Relationship Management" },
    { "_name": "Customer Service" },
    { "_name": "D Programming Language" },
    { "_name": "D3.js" },
    { "_name": "DART" },
    { "_name": "DBMS" },
    { "_name": "DJing" },
    { "_name": "DOS" },
    { "_name": "DVD Mastering" },
    { "_name": "DVD Studio Pro" },
    { "_name": "DaVinci Resolve" },
    { "_name": "Data Analysis" },
    { "_name": "Data Backup" },
    { "_name": "Data Cleansing" },
    { "_name": "Data Entry" },
    { "_name": "Data Ingestion" },
    { "_name": "Data Logistics" },
    { "_name": "Data Mining" },
    { "_name": "Data Modeling" },
    { "_name": "Data Science" },
    { "_name": "Data Scraping" },
    { "_name": "Data Structures" },
    { "_name": "Data Visualization" },
    { "_name": "Data Warehouse" },
    { "_name": "Data Warehousing" },
    { "_name": "DataLife Engine" },
    { "_name": "Database Caching" },
    { "_name": "Database Cataloguing" },
    { "_name": "Database Design" },
    { "_name": "Database Modeling" },
    { "_name": "Database Programming" },
    { "_name": "Database Testing" },
    { "_name": "Databases" },
    { "_name": "Debugging" },
    { "_name": "Delphi" },
    { "_name": "Demandware" },
    { "_name": "Derivatives" },
    { "_name": "Design" },
    { "_name": "Design Patterns" },
    { "_name": "Desktop Applications" },
    { "_name": "Desktop Publishing" },
    { "_name": "DevExpress" },
    { "_name": "DevOps" },
    { "_name": "Device Driver Development" },
    { "_name": "Digital Access Pass" },
    { "_name": "Digital Engineering" },
    { "_name": "Digital Mapping" },
    { "_name": "Digital Marketing" },
    { "_name": "Digital Media" },
    { "_name": "Digital Painting" },
    { "_name": "Digital Photography" },
    { "_name": "Digital Scrapbooking" },
    { "_name": "Digital Signal Processing" },
    { "_name": "DirectShow" },
    { "_name": "DirectX" },
    { "_name": "Disaster Recovery" },
    { "_name": "Distributed Computing" },
    { "_name": "Distributed Systems" },
    { "_name": "Distribution" },
    { "_name": "Django" },
    { "_name": "DocBook" },
    { "_name": "Doctrine ORM" },
    { "_name": "Document Object Model" },
    { "_name": "Documentation" },
    { "_name": "Dojo Toolkit" },
    { "_name": "Domain Migration" },
    { "_name": "DotNetNuke" },
    { "_name": "Drafting" },
    { "_name": "Drawing" },
    { "_name": "Dreamweaver" },
    { "_name": "Dropbox API" },
    { "_name": "Drums" },
    { "_name": "Drupal" },
    { "_name": "Due Diligence" },
    { "_name": "Dwolla API" },
    { "_name": "E-Commerce" },
    { "_name": "ECMAScript" },
    { "_name": "EDGE" },
    { "_name": "ERDAS IMAGINE" },
    { "_name": "Eclipse" },
    { "_name": "Ecommerce" },
    { "_name": "Ecommerce Platform Development" },
    { "_name": "Economics" },
    { "_name": "Edufire" },
    { "_name": "Elasticsearch" },
    { "_name": "Elastix" },
    { "_name": "Electrical Engineering" },
    { "_name": "Electronic Data Interchange (EDI)" },
    { "_name": "Electronic Workbench" },
    { "_name": "Electronics" },
    { "_name": "Elgg" },
    { "_name": "Elliptic Curve Cryptography (ECC)" },
    { "_name": "Email" },
    { "_name": "Email Marketing" },
    { "_name": "Embedded C" },
    { "_name": "Embedded Linux" },
    { "_name": "Embedded Systems" },
    { "_name": "Ember.js" },
    { "_name": "Embroidery" },
    { "_name": "Embroidery Digitization" },
    { "_name": "Engineering" },
    { "_name": "English language" },
    { "_name": "Enterprise JavaBeans (EJB)" },
    { "_name": "Enterprise Software" },
    { "_name": "Entertainment" },
    { "_name": "Entity Framework" },
    { "_name": "Entrepreneurship" },
    { "_name": "Erlang" },
    { "_name": "Erwin" },
    { "_name": "Eucalyptus Cloud" },
    { "_name": "Event Management" },
    { "_name": "Event Planning" },
    { "_name": "Evolus Pencil" },
    { "_name": "Excel VBA" },
    { "_name": "Excellent Communication Skills" },
    { "_name": "Express Scribe" },
    { "_name": "Express.js" },
    { "_name": "Expression Engine" },
    { "_name": "Ext JS" },
    { "_name": "Eyeon Fusion" },
    { "_name": "F#" },
    { "_name": "FBML" },
    { "_name": "FFmpeg" },
    { "_name": "FL Studio" },
    { "_name": "FTP" },
    { "_name": "Fabrication" },
    { "_name": "Facebook API" },
    { "_name": "Facebook Development" },
    { "_name": "Facebook Games Development" },
    { "_name": "Facebook Javascript (FBJS)" },
    { "_name": "Fashion Design" },
    { "_name": "Field-Map" },
    { "_name": "FileMaker" },
    { "_name": "Filing" },
    { "_name": "Film Direction" },
    { "_name": "Film Production" },
    { "_name": "Final Cut Pro" },
    { "_name": "Final Cut Pro X" },
    { "_name": "Finance" },
    { "_name": "Financial" },
    { "_name": "Financial Analysis" },
    { "_name": "Financial Management" },
    { "_name": "Financial Modeling" },
    { "_name": "Financial Reporting" },
    { "_name": "Financial Services" },
    { "_name": "Financial Statements" },
    { "_name": "Fire OS Development" },
    { "_name": "Firebird" },
    { "_name": "Firefox Plugin Development" },
    { "_name": "Firewall" },
    { "_name": "Firmware" },
    { "_name": "Flash" },
    { "_name": "Flash 3D" },
    { "_name": "Flask" },
    { "_name": "Flowcharts" },
    { "_name": "Fluent in Spanish" },
    { "_name": "Flyer Design" },
    { "_name": "Focus" },
    { "_name": "Font Development" },
    { "_name": "FontForge" },
    { "_name": "Forecasting" },
    { "_name": "Foreign Exchange Trading" },
    { "_name": "Form-Z" },
    { "_name": "Format & Layout" },
    { "_name": "Fortran" },
    { "_name": "Forum Development" },
    { "_name": "FourSquare Development" },
    { "_name": "FoxPro Programming" },
    { "_name": "Fraud" },
    { "_name": "FreeMarker" },
    { "_name": "Freeswitch" },
    { "_name": "French language" },
    { "_name": "Front-End Development" },
    { "_name": "Frontend Development" },
    { "_name": "Full Stack Development" },
    { "_name": "Full-text Search Engines" },
    { "_name": "Functional Testing" },
    { "_name": "Fundraising" },
    { "_name": "GIMP" },
    { "_name": "GLSL" },
    { "_name": "GNU Octave" },
    { "_name": "GPS Development" },
    { "_name": "GTK+" },
    { "_name": "GUI Design" },
    { "_name": "Game Design" },
    { "_name": "Game Development" },
    { "_name": "Game Programming" },
    { "_name": "Game Testing" },
    { "_name": "GameSalad Creator" },
    { "_name": "Gamification" },
    { "_name": "GarageBand" },
    { "_name": "Gearman" },
    { "_name": "General Ledger" },
    { "_name": "Genetic Algorithms" },
    { "_name": "Geographic Information System (GIS)" },
    { "_name": "Geolocation" },
    { "_name": "Geometry" },
    { "_name": "Geospatial" },
    { "_name": "German Language" },
    { "_name": "GetResponse" },
    { "_name": "Ggplot2" },
    { "_name": "Git" },
    { "_name": "GitHub" },
    { "_name": "Github" },
    { "_name": "GlassFish" },
    { "_name": "Glassware" },
    { "_name": "Go" },
    { "_name": "GoToMyPC" },
    { "_name": "Golang" },
    { "_name": "GoldMine" },
    { "_name": "Google AdSense API" },
    { "_name": "Google AdWords Development" },
    { "_name": "Google Adwords" },
    { "_name": "Google Analytics" },
    { "_name": "Google Analytics API" },
    { "_name": "Google App Engine" },
    { "_name": "Google App Engine API" },
    { "_name": "Google Apps API" },
    { "_name": "Google Calendar Development" },
    { "_name": "Google Docs API" },
    { "_name": "Google Gadgets" },
    { "_name": "Google Gadgets API" },
    { "_name": "Google Glass" },
    { "_name": "Google Glass SDK" },
    { "_name": "Google Map Maker" },
    { "_name": "Google Maps API" },
    { "_name": "Google Reader API" },
    { "_name": "Google Shopping" },
    { "_name": "Google Sites API" },
    { "_name": "Google Sites Administration" },
    { "_name": "Google Swiffy" },
    { "_name": "Google Web Toolkit" },
    { "_name": "Google+ Development" },
    { "_name": "Google+ Marketing" },
    { "_name": "Gradle" },
    { "_name": "Grails" },
    { "_name": "Graph Databases" },
    { "_name": "Graphic Design" },
    { "_name": "Graphics Programming" },
    { "_name": "Gravity Forms" },
    { "_name": "Groovy" },
    { "_name": "Growth Hacking" },
    { "_name": "GruntJS" },
    { "_name": "HAML" },
    { "_name": "HBase" },
    { "_name": "HP" },
    { "_name": "HP Cloud" },
    { "_name": "HP Network Management Center (HPNMC)" },
    { "_name": "HP QuickTest Professional (HPQTP)" },
    { "_name": "HP-UX Administration" },
    { "_name": "HR" },
    { "_name": "HTML" },
    { "_name": "HTML5" },
    { "_name": "HTTPS" },
    { "_name": "HaXe" },
    { "_name": "Hardware Engineering" },
    { "_name": "Haskell" },
    { "_name": "Help Desk" },
    { "_name": "Heroku" },
    { "_name": "Hibernate" },
    { "_name": "Highcharts" },
    { "_name": "Hindi Language" },
    { "_name": "Hive" },
    { "_name": "Home Automation" },
    { "_name": "Houdini" },
    { "_name": "Human Resources" },
    { "_name": "IBM" },
    { "_name": "IBM AS/400 Control Language" },
    { "_name": "IBM DB2" },
    { "_name": "IBM DB2 Administration" },
    { "_name": "IBM DB2 Programming" },
    { "_name": "IBM Lotus Domino" },
    { "_name": "IBM Lotus Notes Traveler" },
    { "_name": "IBM Lotus Symphony" },
    { "_name": "IBM PowerPC Programming" },
    { "_name": "IBM Rational Rose" },
    { "_name": "IBM SmartCloud" },
    { "_name": "IBM System p" },
    { "_name": "IBM System x" },
    { "_name": "IBM Tivoli Framework" },
    { "_name": "IBM Watson" },
    { "_name": "IBM Websphere" },
    { "_name": "IMS" },
    { "_name": "IMacros" },
    { "_name": "IT Management" },
    { "_name": "IT Service Management" },
    { "_name": "ITIL" },
    { "_name": "Icefaces" },
    { "_name": "Icon Design" },
    { "_name": "Illustration" },
    { "_name": "Image Editing" },
    { "_name": "Image Processing" },
    { "_name": "Imaging" },
    { "_name": "In-Game Advertising" },
    { "_name": "Indexing" },
    { "_name": "Infographics" },
    { "_name": "Informatica" },
    { "_name": "Information Architecture" },
    { "_name": "Information Design" },
    { "_name": "Information Security" },
    { "_name": "Information Technology" },
    { "_name": "Infragistics" },
    { "_name": "Infrastructure" },
    { "_name": "Infusionsoft Development" },
    { "_name": "Inkscape" },
    { "_name": "Inno Setup" },
    { "_name": "Inside Sales" },
    { "_name": "Instagram API" },
    { "_name": "InstallShield" },
    { "_name": "Installer Development" },
    { "_name": "Instructional Design" },
    { "_name": "Instrumentation" },
    { "_name": "Insurance" },
    { "_name": "Integrated Circuits" },
    { "_name": "Integration Testing" },
    { "_name": "Integrity" },
    { "_name": "IntelliJ IDEA" },
    { "_name": "Interaction Design" },
    { "_name": "Interactive Voice Response" },
    { "_name": "Interface Design" },
    { "_name": "Internet" },
    { "_name": "Internet Information Services (IIS)" },
    { "_name": "Internet Security" },
    { "_name": "Interspire" },
    { "_name": "Intranet Architecture" },
    { "_name": "Intranet Implementation" },
    { "_name": "Inventory" },
    { "_name": "Inventory Control" },
    { "_name": "Inventory Management" },
    { "_name": "Investment Banking" },
    { "_name": "Invitation Design" },
    { "_name": "Ionic Framework" },
    { "_name": "Issue Tracking Systems" },
    { "_name": "J2EE" },
    { "_name": "J2ME" },
    { "_name": "J2SE" },
    { "_name": "JAXB" },
    { "_name": "JBPM" },
    { "_name": "JBoss" },
    { "_name": "JBoss Seam" },
    { "_name": "JCL" },
    { "_name": "JDBC" },
    { "_name": "JDeveloper" },
    { "_name": "JMeter" },
    { "_name": "JNCIA-Junos" },
    { "_name": "JNDI" },
    { "_name": "JOOMLA" },
    { "_name": "JPA" },
    { "_name": "JQuery Mobile" },
    { "_name": "JSON" },
    { "_name": "JSP" },
    { "_name": "JSTL" },
    { "_name": "JUNIT" },
    { "_name": "JUnit" },
    { "_name": "JasperReports" },
    { "_name": "Java" },
    { "_name": "Java EE" },
    { "_name": "Java ME" },
    { "_name": "Java Remote Method Invocation (Java RMI)" },
    { "_name": "Java Servlets Development" },
    { "_name": "JavaFX" },
    { "_name": "JavaScript" },
    { "_name": "JavaServer Faces (JSF)" },
    { "_name": "Jenkins" },
    { "_name": "JetPack" },
    { "_name": "Jimdo" },
    { "_name": "Jingle Program Production" },
    { "_name": "Jinja2" },
    { "_name": "Jira" },
    { "_name": "JomSocial Development" },
    { "_name": "Joomla" },
    { "_name": "Joomla Fabrik" },
    { "_name": "Joomla Migration" },
    { "_name": "Jsharp" },
    { "_name": "KVM" },
    { "_name": "Kajabi" },
    { "_name": "Kanban" },
    { "_name": "Kannada" },
    { "_name": "Kendo UI" },
    { "_name": "Kentico CMS" },
    { "_name": "Kernel" },
    { "_name": "Keyboarding" },
    { "_name": "Keynote" },
    { "_name": "Kindle App Development" },
    { "_name": "Kindle Fire" },
    { "_name": "KnockoutJS" },
    { "_name": "Kohana" },
    { "_name": "Korn Shell" },
    { "_name": "LAMP" },
    { "_name": "LAMP Administration" },
    { "_name": "LESS" },
    { "_name": "LINQ" },
    { "_name": "LINQ to Entities" },
    { "_name": "LINQ to SQL" },
    { "_name": "LabVIEW" },
    { "_name": "Label and Package Design" },
    { "_name": "Landing Pages" },
    { "_name": "Laravel Framework" },
    { "_name": "Layout" },
    { "_name": "Lead Generation" },
    { "_name": "Leadership" },
    { "_name": "Leadership Development" },
    { "_name": "Leadership and Team Inspiration" },
    { "_name": "Lean Consulting" },
    { "_name": "Lean Startups" },
    { "_name": "Learning Management System (LMS)" },
    { "_name": "Lectora" },
    { "_name": "Legal" },
    { "_name": "LemonStand" },
    { "_name": "Lettering" },
    { "_name": "Level Design" },
    { "_name": "Licensing" },
    { "_name": "Liferay" },
    { "_name": "LightWave 3D" },
    { "_name": "Lightworks" },
    { "_name": "LimeJS" },
    { "_name": "LimeSurvey" },
    { "_name": "Linear Programming" },
    { "_name": "LinkedIn Development" },
    { "_name": "Linux" },
    { "_name": "LiquidPlanner" },
    { "_name": "Lisp" },
    { "_name": "Lithium Framework" },
    { "_name": "Load Testing" },
    { "_name": "LoadRunner" },
    { "_name": "Log4j" },
    { "_name": "LogiXML" },
    { "_name": "Logic Pro" },
    { "_name": "Logistics" },
    { "_name": "Logo Design" },
    { "_name": "Lotus Approach" },
    { "_name": "Lotus Notes" },
    { "_name": "Lua" },
    { "_name": "Lucene Search" },
    { "_name": "MAGENTO" },
    { "_name": "MBA" },
    { "_name": "MIDI" },
    { "_name": "MODX" },
    { "_name": "MQL 4" },
    { "_name": "MS Office" },
    { "_name": "MVC" },
    { "_name": "MVC Framework" },
    { "_name": "MXML" },
    { "_name": "Mac OS App Development" },
    { "_name": "Mac OS X" },
    { "_name": "Mac OSX Administration" },
    { "_name": "Macaw" },
    { "_name": "Machine Design" },
    { "_name": "Machine Learning" },
    { "_name": "MadCap Software" },
    { "_name": "Magazine Layout" },
    { "_name": "Magento" },
    { "_name": "Magic Bullet Colorista" },
    { "_name": "Magic Tricks" },
    { "_name": "MailChimp" },
    { "_name": "Make Build Script" },
    { "_name": "Malware" },
    { "_name": "Mambo" },
    { "_name": "Management" },
    { "_name": "Management Consulting" },
    { "_name": "Manga" },
    { "_name": "Mantis" },
    { "_name": "Manual Test Execution" },
    { "_name": "Manual Testing" },
    { "_name": "Manufacturing" },
    { "_name": "MapReduce" },
    { "_name": "Mapinfo" },
    { "_name": "Mapr" },
    { "_name": "Market Research" },
    { "_name": "Marketing" },
    { "_name": "Marketing Management" },
    { "_name": "Marketing Strategy" },
    { "_name": "Matlab" },
    { "_name": "Maven" },
    { "_name": "McAfee VirusScan" },
    { "_name": "Mechanical Engineering" },
    { "_name": "Mechanical Turk API" },
    { "_name": "Media Relations" },
    { "_name": "Medical" },
    { "_name": "Medical Illustration" },
    { "_name": "Medical Imaging" },
    { "_name": "Medical Informatics" },
    { "_name": "Memcached" },
    { "_name": "Menu Design" },
    { "_name": "Merchandising" },
    { "_name": "MerchantRun" },
    { "_name": "MerchantRun GlobalLink" },
    { "_name": "Mercurial" },
    { "_name": "Messaging" },
    { "_name": "MetaTrader 4 (MT4)" },
    { "_name": "Meteor" },
    { "_name": "Metrics" },
    { "_name": "MicroStrategy" },
    { "_name": "Microcontroller Programming" },
    { "_name": "Microsoft" },
    { "_name": "Microsoft .NET" },
    { "_name": "Microsoft Access" },
    { "_name": "Microsoft Access Administration" },
    { "_name": "Microsoft Access Programming" },
    { "_name": "Microsoft Active Directory" },
    { "_name": "Microsoft Dynamics Administration" },
    { "_name": "Microsoft Dynamics CRM" },
    { "_name": "Microsoft Dynamics Development" },
    { "_name": "Microsoft Dynamics ERP" },
    { "_name": "Microsoft Dynamics GP" },
    { "_name": "Microsoft Entity Framework" },
    { "_name": "Microsoft Excel" },
    { "_name": "Microsoft Exchange" },
    { "_name": "Microsoft Foundation Classes (MFC)" },
    { "_name": "Microsoft Infopath" },
    { "_name": "Microsoft Kinect Development" },
    { "_name": "Microsoft Message Queue Server (MMSQ)" },
    { "_name": "Microsoft Office" },
    { "_name": "Microsoft Office SharePoint Server" },
    { "_name": "Microsoft Outlook" },
    { "_name": "Microsoft Outlook Development" },
    { "_name": "Microsoft PowerPoint" },
    { "_name": "Microsoft Project" },
    { "_name": "Microsoft Publisher" },
    { "_name": "Microsoft SQL SSAS" },
    { "_name": "Microsoft SQL SSRS" },
    { "_name": "Microsoft SQL Server" },
    { "_name": "Microsoft SQL Server Notification Services" },
    { "_name": "Microsoft SQL Server Programming" },
    { "_name": "Microsoft SharePoint Administration" },
    { "_name": "Microsoft SharePoint Designer" },
    { "_name": "Microsoft SharePoint Development" },
    { "_name": "Microsoft Silverlight" },
    { "_name": "Microsoft Visio" },
    { "_name": "Microsoft Visual Basic" },
    { "_name": "Microsoft Visual C++" },
    { "_name": "Microsoft Visual Studio" },
    { "_name": "Microsoft Visual Studio LightSwitch" },
    { "_name": "Microsoft Windows" },
    { "_name": "Microsoft Windows Azure" },
    { "_name": "Microsoft Windows Media Connect" },
    { "_name": "Microsoft Windows Movie Maker" },
    { "_name": "Microsoft Windows Phone 7 App Development" },
    { "_name": "Microsoft Windows Template Library" },
    { "_name": "Microsoft Windows Workflow Foundation" },
    { "_name": "Microsoft Word" },
    { "_name": "Microstock Photography" },
    { "_name": "Middleware" },
    { "_name": "Minecraft" },
    { "_name": "Mining" },
    { "_name": "Mobile" },
    { "_name": "Mobile Advertising" },
    { "_name": "Mobile App Development" },
    { "_name": "Mobile App Testing" },
    { "_name": "Mobile Application Design" },
    { "_name": "Mobile Application Development" },
    { "_name": "Mobile Development" },
    { "_name": "Mobile Development Framework" },
    { "_name": "Mobile Programming" },
    { "_name": "Mobile UI Design" },
    { "_name": "Mocha" },
    { "_name": "Mockito" },
    { "_name": "Model Sheet Drawing" },
    { "_name": "Model View ViewModel (MVVM)" },
    { "_name": "MongoDB" },
    { "_name": "Monitoring" },
    { "_name": "Mono" },
    { "_name": "Moodle" },
    { "_name": "Mootools" },
    { "_name": "Motion Graphics" },
    { "_name": "MovableType" },
    { "_name": "Mozenda Scraper" },
    { "_name": "Ms Project" },
    { "_name": "Multi-touch Hardware Programming" },
    { "_name": "Multimedia" },
    { "_name": "Multithreaded Programming" },
    { "_name": "Murals" },
    { "_name": "Music" },
    { "_name": "Music Arrangement" },
    { "_name": "Music Dubbing" },
    { "_name": "Music Producing" },
    { "_name": "Musical Composition" },
    { "_name": "MySQL" },
    { "_name": "MySQL Administration" },
    { "_name": "MySQL Programming" },
    { "_name": "NHibernate" },
    { "_name": "NUKE" },
    { "_name": "NVIDIA Mental Ray" },
    { "_name": "Narration" },
    { "_name": "Natural Language Processing" },
    { "_name": "Navigation System Design" },
    { "_name": "Navigation System Implementation" },
    { "_name": "Negotiation" },
    { "_name": "Neo4j" },
    { "_name": "NetBeans" },
    { "_name": "NetSuite Development" },
    { "_name": "Netbeans" },
    { "_name": "Network Pentesting" },
    { "_name": "Network Programming" },
    { "_name": "Network Security" },
    { "_name": "Networking" },
    { "_name": "New Business Development" },
    { "_name": "Nginx" },
    { "_name": "Ning Development" },
    { "_name": "NoSQL" },
    { "_name": "Node.js" },
    { "_name": "Non-Disclosure Agreements" },
    { "_name": "Non-Linear Editing System" },
    { "_name": "NopCommerce" },
    { "_name": "Novell NetWare" },
    { "_name": "OAuth" },
    { "_name": "OCR Algorithms" },
    { "_name": "OCR Tesseract" },
    { "_name": "OCaml" },
    { "_name": "ODBC" },
    { "_name": "OGRE" },
    { "_name": "OLAP" },
    { "_name": "OOPS" },
    { "_name": "ORM" },
    { "_name": "OSGi" },
    { "_name": "Object Oriented Design" },
    { "_name": "Object Oriented PHP" },
    { "_name": "Object Oriented Programming" },
    { "_name": "Object Oriented Programming (OOP)" },
    { "_name": "Object Pascal" },
    { "_name": "Objective-C" },
    { "_name": "Objective-J" },
    { "_name": "Oil Painting" },
    { "_name": "OmniGraffle" },
    { "_name": "Online Marketing" },
    { "_name": "OpenBSD" },
    { "_name": "OpenBravo PoS" },
    { "_name": "OpenCV" },
    { "_name": "OpenCart" },
    { "_name": "OpenEMM" },
    { "_name": "OpenERP Administration" },
    { "_name": "OpenERP Development" },
    { "_name": "OpenGL" },
    { "_name": "OpenGL ES" },
    { "_name": "OpenLayers" },
    { "_name": "OpenStack" },
    { "_name": "OpenTok Development" },
    { "_name": "OpenType" },
    { "_name": "OpenVBX" },
    { "_name": "OpenVMS" },
    { "_name": "OpenWrt" },
    { "_name": "OpenX" },
    { "_name": "Operating Systems" },
    { "_name": "Operations Management" },
    { "_name": "Optimizepress" },
    { "_name": "Orace OBIEE Plus" },
    { "_name": "Oracle" },
    { "_name": "Oracle 10g" },
    { "_name": "Oracle APEX" },
    { "_name": "Oracle ATG Web Commerce" },
    { "_name": "Oracle Agile" },
    { "_name": "Oracle Application Framework" },
    { "_name": "Oracle Application Server" },
    { "_name": "Oracle BRM" },
    { "_name": "Oracle CRM On Demand" },
    { "_name": "Oracle Complex Events Processing" },
    { "_name": "Oracle Data Guard" },
    { "_name": "Oracle Database" },
    { "_name": "Oracle Demantra" },
    { "_name": "Oracle E-Business Suite" },
    { "_name": "Oracle Endeca" },
    { "_name": "Oracle Enterprise Service Bus" },
    { "_name": "Oracle Forms" },
    { "_name": "Oracle Fusion Applications" },
    { "_name": "Oracle Fusion Middleware" },
    { "_name": "Oracle Hyperion Planning" },
    { "_name": "Oracle Java EE" },
    { "_name": "Oracle PLSQL" },
    { "_name": "Oracle Patching" },
    { "_name": "Oracle Performance Tuning" },
    { "_name": "Oracle Policy Automation" },
    { "_name": "Oracle Primavera" },
    { "_name": "Oracle Programming" },
    { "_name": "Oracle RightNow" },
    { "_name": "Oracle SOA Suite" },
    { "_name": "Oracle Sun Ray" },
    { "_name": "Oracle Taleo" },
    { "_name": "Oracle Team Productivity Center" },
    { "_name": "Oracle Transportation Management" },
    { "_name": "Oracle Unified Method" },
    { "_name": "Oracle Universal Content Management" },
    { "_name": "Oracle Upgrade" },
    { "_name": "Oracle User Productivity Kit" },
    { "_name": "Oracle WebLogic" },
    { "_name": "OrangeCRM" },
    { "_name": "Orchard CMS" },
    { "_name": "OsCommerce" },
    { "_name": "Outside Sales" },
    { "_name": "Outsourcing" },
    { "_name": "P&L" },
    { "_name": "PC" },
    { "_name": "PDF Conversion" },
    { "_name": "PHP" },
    { "_name": "PHP-Nuke" },
    { "_name": "PLC & SCADA" },
    { "_name": "PLC Programming" },
    { "_name": "PMP" },
    { "_name": "POS" },
    { "_name": "POS Terminal Development" },
    { "_name": "PRADO PHP Framework" },
    { "_name": "PSD to HTML" },
    { "_name": "PSD to MailChimp" },
    { "_name": "PSD to Wordpress" },
    { "_name": "PSD to XHTML" },
    { "_name": "PSD2CMS" },
    { "_name": "PSPICE" },
    { "_name": "PTGui" },
    { "_name": "Packaging" },
    { "_name": "Packaging Design" },
    { "_name": "Palm" },
    { "_name": "Palm App Development" },
    { "_name": "Palm webOS Application Development" },
    { "_name": "Panoramic Stitching" },
    { "_name": "Papercraft" },
    { "_name": "Papervision3D" },
    { "_name": "Parallels Virtual Desktop" },
    { "_name": "Parse Mobile App Platform" },
    { "_name": "ParticleIllusion" },
    { "_name": "Pascal" },
    { "_name": "PayPal Development" },
    { "_name": "Payment Gateway Integration" },
    { "_name": "Payment Processing" },
    { "_name": "Paypal Integration" },
    { "_name": "Payroll" },
    { "_name": "Pentaho" },
    { "_name": "People Management" },
    { "_name": "PeopleSoft" },
    { "_name": "Perforce" },
    { "_name": "Performance Testing" },
    { "_name": "Performance Tuning" },
    { "_name": "Performing Arts" },
    { "_name": "Perl" },
    { "_name": "Perl Catalyst" },
    { "_name": "Perl Mojolicious" },
    { "_name": "PerlDancer" },
    { "_name": "Pervasive Software" },
    { "_name": "Pharmaceutical" },
    { "_name": "PhoneGap" },
    { "_name": "Photo Editing" },
    { "_name": "Photo Manipulation" },
    { "_name": "Photo Retouching" },
    { "_name": "PhotoScape" },
    { "_name": "Photograph Color Correction" },
    { "_name": "Photography" },
    { "_name": "Photoshop" },
    { "_name": "PhpBB" },
    { "_name": "Physics" },
    { "_name": "Pig" },
    { "_name": "Planning" },
    { "_name": "Platform Migration" },
    { "_name": "Play Framework" },
    { "_name": "Pligg" },
    { "_name": "Plivo" },
    { "_name": "Polymer Clay Sculpting" },
    { "_name": "Portfolio Management" },
    { "_name": "Portlets" },
    { "_name": "Portrait Painting" },
    { "_name": "PostScript" },
    { "_name": "Poster Design" },
    { "_name": "PostgreSQL" },
    { "_name": "PostgreSQL Administration" },
    { "_name": "PostgreSQL Programming" },
    { "_name": "Power Builder" },
    { "_name": "PreSonus Studio One" },
    { "_name": "Prepress" },
    { "_name": "Presentation Design" },
    { "_name": "Presentation Skills" },
    { "_name": "Presentations" },
    { "_name": "PrestaShop" },
    { "_name": "Prezi" },
    { "_name": "Pricing" },
    { "_name": "PrimeFaces" },
    { "_name": "Print Design" },
    { "_name": "Print Layout Design" },
    { "_name": "Private Clouds" },
    { "_name": "Private Equity" },
    { "_name": "ProTools" },
    { "_name": "Problem Solving" },
    { "_name": "Problem Solving Skills" },
    { "_name": "Process Improvement" },
    { "_name": "Process Management" },
    { "_name": "Procurement" },
    { "_name": "Product Design" },
    { "_name": "Product Development" },
    { "_name": "Product Launch" },
    { "_name": "Product Management" },
    { "_name": "Product Marketing" },
    { "_name": "Product Strategy" },
    { "_name": "Professional Services" },
    { "_name": "Program Management" },
    { "_name": "Program Manager" },
    { "_name": "Programming" },
    { "_name": "Project Coordinator" },
    { "_name": "Project Leader" },
    { "_name": "Project Management" },
    { "_name": "Project Manager" },
    { "_name": "Project Scheduling" },
    { "_name": "Prolog" },
    { "_name": "Proofreading" },
    { "_name": "Propellerhead Reason" },
    { "_name": "Prototype Javascript Framework" },
    { "_name": "Public Relations" },
    { "_name": "Public Speaking" },
    { "_name": "Publications" },
    { "_name": "Publishing" },
    { "_name": "Publishing Fundamentals" },
    { "_name": "Puppet Administration" },
    { "_name": "Purchasing" },
    { "_name": "PyQt" },
    { "_name": "Pylons" },
    { "_name": "Python" },
    { "_name": "Python Numpy" },
    { "_name": "Python SciPy" },
    { "_name": "QA Engineering" },
    { "_name": "QA Management" },
    { "_name": "Qt" },
    { "_name": "Quality" },
    { "_name": "Quality Assurance" },
    { "_name": "Quality Control" },
    { "_name": "Quality Management" },
    { "_name": "Quark Xpress" },
    { "_name": "Quartz Scheduler" },
    { "_name": "Quick Books" },
    { "_name": "Quickbooks" },
    { "_name": "R" },
    { "_name": "R-Hadoop" },
    { "_name": "RADIUS" },
    { "_name": "RDBMS" },
    { "_name": "REST" },
    { "_name": "RESTful Services" },
    { "_name": "RETS" },
    { "_name": "RPG Development" },
    { "_name": "RSS" },
    { "_name": "RSpec" },
    { "_name": "RTL" },
    { "_name": "RTML" },
    { "_name": "Rackspace" },
    { "_name": "Radiant CMS" },
    { "_name": "Radio Broadcasting" },
    { "_name": "Radio Personality" },
    { "_name": "Raphael JS" },
    { "_name": "Rapid Miner" },
    { "_name": "Rapid Prototyping" },
    { "_name": "Raspberry Pi" },
    { "_name": "Rational Unified Process (RUP)" },
    { "_name": "Razor Template Engine" },
    { "_name": "React.js" },
    { "_name": "Real Estate" },
    { "_name": "Real Estate IDX" },
    { "_name": "Real Time Stream Processing" },
    { "_name": "Realbasic" },
    { "_name": "Realist Painting" },
    { "_name": "Recommender Systems" },
    { "_name": "Reconciliations" },
    { "_name": "Recruiter" },
    { "_name": "Recruiting" },
    { "_name": "Red Hat Certified Engineer (RHCE)" },
    { "_name": "Red5" },
    { "_name": "Redhat" },
    { "_name": "Redis" },
    { "_name": "Redmine" },
    { "_name": "Refinery CMS" },
    { "_name": "Regression Testing" },
    { "_name": "Regular Expressions" },
    { "_name": "Relational Databases" },
    { "_name": "Relationship Building" },
    { "_name": "Reliability" },
    { "_name": "Remote Sensing" },
    { "_name": "Requirement Management" },
    { "_name": "Requirements Analysis" },
    { "_name": "Research" },
    { "_name": "Research and Development" },
    { "_name": "Resin" },
    { "_name": "Resource Description Framework (RDF)" },
    { "_name": "Responsive Web Design" },
    { "_name": "Retail" },
    { "_name": "Retention" },
    { "_name": "Reverse Engineering" },
    { "_name": "Rhodes Framework" },
    { "_name": "Risk Analysis" },
    { "_name": "Risk Assessment" },
    { "_name": "Risk Management" },
    { "_name": "Robot Framework" },
    { "_name": "Robotics" },
    { "_name": "Root Cause Analysis" },
    { "_name": "Rotoscoping" },
    { "_name": "Routers" },
    { "_name": "Ruby" },
    { "_name": "Ruby on Rails" },
    { "_name": "Russian Language" },
    { "_name": "Russian language" },
    { "_name": "S" },
    { "_name": "SAP" },
    { "_name": "SAP ABAP" },
    { "_name": "SAP BSP" },
    { "_name": "SAP Business Objects" },
    { "_name": "SAP CRM" },
    { "_name": "SAP Crystal Reports" },
    { "_name": "SAP ERP" },
    { "_name": "SAP Logistics Execution" },
    { "_name": "SAP SD" },
    { "_name": "SAS" },
    { "_name": "SCADA" },
    { "_name": "SCORM" },
    { "_name": "SCRUM" },
    { "_name": "SDK" },
    { "_name": "SDLC" },
    { "_name": "SDLX" },
    { "_name": "SEO" },
    { "_name": "SEO/SEM" },
    { "_name": "SIP" },
    { "_name": "SMPP" },
    { "_name": "SMS" },
    { "_name": "SMS Gateway" },
    { "_name": "SMTP" },
    { "_name": "SOAP" },
    { "_name": "SPSS" },
    { "_name": "SQA" },
    { "_name": "SQL" },
    { "_name": "SQL Azure" },
    { "_name": "SQL CLR" },
    { "_name": "SQL Programming" },
    { "_name": "SQL Server" },
    { "_name": "SQL Server Integration Services (SSIS)" },
    { "_name": "SQLite" },
    { "_name": "SQLite Administration" },
    { "_name": "SQLite Programming" },
    { "_name": "SQR" },
    { "_name": "SSH" },
    { "_name": "SSI" },
    { "_name": "SSL" },
    { "_name": "SWT" },
    { "_name": "SaaS" },
    { "_name": "Sage ERP Accpac" },
    { "_name": "Sales" },
    { "_name": "Sales Management" },
    { "_name": "Sales Strategy and Management" },
    { "_name": "Sales Support" },
    { "_name": "Sales Training" },
    { "_name": "Sales and Marketing" },
    { "_name": "Sales/Marketing and Strategic Partnerships" },
    { "_name": "Salesforce" },
    { "_name": "Salesforce Apex" },
    { "_name": "Salesforce App Development" },
    { "_name": "Salesforce.com" },
    { "_name": "Sass" },
    { "_name": "Scala" },
    { "_name": "Scenario Planning" },
    { "_name": "Scheduling" },
    { "_name": "Scheme" },
    { "_name": "Science" },
    { "_name": "Scientific Computation" },
    { "_name": "ScrapeBox" },
    { "_name": "Scrapy" },
    { "_name": "Scripting" },
    { "_name": "Scripting Languages" },
    { "_name": "Scripts & Utilities" },
    { "_name": "Scrum" },
    { "_name": "Scrum Master" },
    { "_name": "Section 508 Compliance" },
    { "_name": "Securities" },
    { "_name": "Security" },
    { "_name": "Selenium" },
    { "_name": "Selenium WebDriver" },
    { "_name": "Sencha GXT" },
    { "_name": "Sencha Touch" },
    { "_name": "Sendmail" },
    { "_name": "Sentiment Analysis" },
    { "_name": "Sequential Art" },
    { "_name": "Serial Port Interfacing" },
    { "_name": "Serialization" },
    { "_name": "Servers" },
    { "_name": "Services" },
    { "_name": "Servlets" },
    { "_name": "SharePoint" },
    { "_name": "Shell Scripting" },
    { "_name": "ShiVa3D" },
    { "_name": "Shopify" },
    { "_name": "Shopify Templates" },
    { "_name": "SigmaPlot" },
    { "_name": "Silex Framework" },
    { "_name": "SilverStripe" },
    { "_name": "Simple DirectMedia Layer" },
    { "_name": "Sinatra Framework" },
    { "_name": "Singing" },
    { "_name": "SiteBuildIt" },
    { "_name": "Sitecore" },
    { "_name": "SkaDate" },
    { "_name": "Sketch" },
    { "_name": "Sketching" },
    { "_name": "Skype Development" },
    { "_name": "Slackware Linux" },
    { "_name": "SmartFoxServer" },
    { "_name": "Smarty" },
    { "_name": "Snort" },
    { "_name": "Social Media" },
    { "_name": "Social Media Marketing" },
    { "_name": "Social Media Strategy" },
    { "_name": "Social Networking" },
    { "_name": "Social Networking Development" },
    { "_name": "SocialEngine" },
    { "_name": "Socket Programming" },
    { "_name": "Software" },
    { "_name": "Software Architecture" },
    { "_name": "Software Configuration Management" },
    { "_name": "Software Debugging" },
    { "_name": "Software Design" },
    { "_name": "Software Development" },
    { "_name": "Software Documentation" },
    { "_name": "Software Engineering" },
    { "_name": "Software Licensing" },
    { "_name": "Software QA Testing" },
    { "_name": "Software Testing" },
    { "_name": "Solidworks" },
    { "_name": "Sony Vegas" },
    { "_name": "Sound Design" },
    { "_name": "Sound Editing" },
    { "_name": "Sound Effects" },
    { "_name": "Sound Forge" },
    { "_name": "Sourcing" },
    { "_name": "SpamAssassin" },
    { "_name": "Sparx Systems Enterprise Architect" },
    { "_name": "Sphinx" },
    { "_name": "Spine JS" },
    { "_name": "Sports" },
    { "_name": "Spree" },
    { "_name": "Spring" },
    { "_name": "Spring Boot" },
    { "_name": "Spring Framework" },
    { "_name": "Spring Security" },
    { "_name": "SquareSpace" },
    { "_name": "Stakeholder Management" },
    { "_name": "Standard Template Library (STL)" },
    { "_name": "Start-Ups" },
    { "_name": "Startups" },
    { "_name": "Stationery Design" },
    { "_name": "Statistical Analysis" },
    { "_name": "Statistics" },
    { "_name": "Steinberg Cubase" },
    { "_name": "Stenography" },
    { "_name": "Sticker Design" },
    { "_name": "Still Life Painting" },
    { "_name": "Stored procedures" },
    { "_name": "Storyboarding" },
    { "_name": "Strategic Partnerships" },
    { "_name": "Strategic Planning" },
    { "_name": "Stream Processing" },
    { "_name": "Stripe" },
    { "_name": "Strong Work Ethic" },
    { "_name": "Struts" },
    { "_name": "Style Guide Development" },
    { "_name": "Subversion" },
    { "_name": "SugarCRM Development" },
    { "_name": "Supply Chain Management" },
    { "_name": "Support" },
    { "_name": "SurveyMonkey" },
    { "_name": "Svn" },
    { "_name": "Swift" },
    { "_name": "Swing" },
    { "_name": "Symbian Development" },
    { "_name": "Symfony" },
    { "_name": "Synthetic Aperture Color Finesse" },
    { "_name": "System Administration" },
    { "_name": "System Analysis" },
    { "_name": "System Automation" },
    { "_name": "System Design" },
    { "_name": "System testing" },
    { "_name": "Systems Administration" },
    { "_name": "Systems Development" },
    { "_name": "T-Shirt Design" },
    { "_name": "TCP/IP" },
    { "_name": "TDD" },
    { "_name": "TFS" },
    { "_name": "TYPO3" },
    { "_name": "Tableau" },
    { "_name": "Tableau Software" },
    { "_name": "Talend Open Studio" },
    { "_name": "Talent Acquisition" },
    { "_name": "Talent Management" },
    { "_name": "Tamil language" },
    { "_name": "Tastypie" },
    { "_name": "Taxonomy" },
    { "_name": "Teaching Algebra" },
    { "_name": "Teaching Mathematics" },
    { "_name": "Team Building" },
    { "_name": "Team Foundation Server" },
    { "_name": "Team Lead" },
    { "_name": "Team Player" },
    { "_name": "Teamwork" },
    { "_name": "Technical Support" },
    { "_name": "Technical Writing" },
    { "_name": "Telecommunications" },
    { "_name": "Telerik" },
    { "_name": "Telerik Sitefinity CMS" },
    { "_name": "Templates" },
    { "_name": "Tesseract" },
    { "_name": "Test" },
    { "_name": "Test Automation" },
    { "_name": "Test Case Design" },
    { "_name": "Test Cases" },
    { "_name": "Test Driven Development" },
    { "_name": "Test Plans" },
    { "_name": "TestComplete" },
    { "_name": "TestLink" },
    { "_name": "Testing Framework" },
    { "_name": "Textile Engineering" },
    { "_name": "Textpattern" },
    { "_name": "Thai" },
    { "_name": "The Foundry NUKE" },
    { "_name": "Time Management" },
    { "_name": "Tizen" },
    { "_name": "Tk" },
    { "_name": "Toon Boom Harmony" },
    { "_name": "Toon Boom Studio" },
    { "_name": "Tornado" },
    { "_name": "Tortoise SVN" },
    { "_name": "Trade Show Exhibition Design" },
    { "_name": "Training" },
    { "_name": "Transact-SQL" },
    { "_name": "Transportation" },
    { "_name": "Travel" },
    { "_name": "Tropo" },
    { "_name": "Troubleshooting" },
    { "_name": "Twig" },
    { "_name": "Twilio API" },
    { "_name": "Twitter API" },
    { "_name": "Twitter Bootstrap" },
    { "_name": "TypeScript" },
    { "_name": "Typesetting" },
    { "_name": "Typing" },
    { "_name": "Typography" },
    { "_name": "UI/UX Design" },
    { "_name": "UML" },
    { "_name": "Ubercart" },
    { "_name": "Ubuntu" },
    { "_name": "Ulead VideoStudio" },
    { "_name": "Umbraco" },
    { "_name": "Unified Modeling Language" },
    { "_name": "Unify" },
    { "_name": "Unit Testing" },
    { "_name": "Unity" },
    { "_name": "Unix" },
    { "_name": "Unix Shell" },
    { "_name": "Unreal Engine" },
    { "_name": "UnrealScript" },
    { "_name": "Urban Design" },
    { "_name": "Usability Testing" },
    { "_name": "Use Cases" },
    { "_name": "User Acceptance Testing" },
    { "_name": "User Experience Design" },
    { "_name": "User Interface" },
    { "_name": "User Interface Design" },
    { "_name": "User Research" },
    { "_name": "Utilities" },
    { "_name": "VB.NET" },
    { "_name": "VBA" },
    { "_name": "VBScript" },
    { "_name": "VBulletin" },
    { "_name": "VFX Animation" },
    { "_name": "VFX Design" },
    { "_name": "VHDL" },
    { "_name": "VICIDIAL" },
    { "_name": "VMware" },
    { "_name": "VOIP Software" },
    { "_name": "VTK" },
    { "_name": "Vaadin Framework" },
    { "_name": "VectorWorks" },
    { "_name": "Vendor Management" },
    { "_name": "Venture Capital" },
    { "_name": "Verilog" },
    { "_name": "Version Control" },
    { "_name": "Vertica" },
    { "_name": "Video" },
    { "_name": "Video Conversion" },
    { "_name": "Video Editing" },
    { "_name": "Video Post Editing" },
    { "_name": "Video Production" },
    { "_name": "Video Publishing" },
    { "_name": "Video Sales Letter" },
    { "_name": "Video Streaming" },
    { "_name": "Video Upload" },
    { "_name": "Videography" },
    { "_name": "Virtual Currency" },
    { "_name": "Virtual Machine" },
    { "_name": "Virtual Storage Access Method (VSAM)" },
    { "_name": "Virtualization" },
    { "_name": "VirtueMart" },
    { "_name": "Virtuoso" },
    { "_name": "Visio" },
    { "_name": "Visual Arts" },
    { "_name": "Visual Basic" },
    { "_name": "Visual Dataflex" },
    { "_name": "Visual Design" },
    { "_name": "Visual FoxPro" },
    { "_name": "Visualforce" },
    { "_name": "VoiceXML" },
    { "_name": "Volusion" },
    { "_name": "WAMP" },
    { "_name": "WEB" },
    { "_name": "WHMCS Development" },
    { "_name": "Watercolor Painting" },
    { "_name": "Web Analytics" },
    { "_name": "Web Application Frameworks" },
    { "_name": "Web Applications" },
    { "_name": "Web Crawler" },
    { "_name": "Web Crawling" },
    { "_name": "Web Design" },
    { "_name": "Web Development" },
    { "_name": "Web Host Manager" },
    { "_name": "Web Hosting" },
    { "_name": "Web Programming" },
    { "_name": "Web Scraping" },
    { "_name": "Web Services" },
    { "_name": "Web Services Development" },
    { "_name": "Web Technologies" },
    { "_name": "Web Testing" },
    { "_name": "WebApp Pentesting" },
    { "_name": "WebGL" },
    { "_name": "Webflow" },
    { "_name": "Webisode Production" },
    { "_name": "Website Development" },
    { "_name": "Website Prototyping" },
    { "_name": "Website Wireframing" },
    { "_name": "Weebly" },
    { "_name": "Weka" },
    { "_name": "Whiteboard Animation" },
    { "_name": "Wholesale" },
    { "_name": "WiX" },
    { "_name": "Wicket" },
    { "_name": "Wilcom Embroidery Digitization" },
    { "_name": "Wilcom EmbroideryStudio" },
    { "_name": "Win32 App Development" },
    { "_name": "WinDev" },
    { "_name": "WinDev Mobile" },
    { "_name": "Windows 7" },
    { "_name": "Windows 8 App Development" },
    { "_name": "Windows App Development" },
    { "_name": "Windows Communication Foundation (WCF)" },
    { "_name": "Windows Forms Development" },
    { "_name": "Windows Mobile" },
    { "_name": "Windows Phone" },
    { "_name": "Windows Presentation Foundation (WPF)" },
    { "_name": "Windows XP" },
    { "_name": "Winsock" },
    { "_name": "Wireframing" },
    { "_name": "Wireless" },
    { "_name": "Wireshark" },
    { "_name": "Woocommerce" },
    { "_name": "WordPress" },
    { "_name": "WordPress e-Commerce" },
    { "_name": "Wordpress" },
    { "_name": "Wordpress Plugin" },
    { "_name": "Worldbuilding" },
    { "_name": "Worldspan" },
    { "_name": "Wowza Media Server" },
    { "_name": "Wrap Advertising" },
    { "_name": "Writing" },
    { "_name": "Written communication" },
    { "_name": "WxWidgets" },
    { "_name": "X-Cart" },
    { "_name": "X86 Assembly Language" },
    { "_name": "XAML" },
    { "_name": "XHTML" },
    { "_name": "XML" },
    { "_name": "XML Web Services" },
    { "_name": "XML-RPC" },
    { "_name": "XMPP" },
    { "_name": "XPath" },
    { "_name": "XQuery" },
    { "_name": "XSD" },
    { "_name": "XSL" },
    { "_name": "XSLT" },
    { "_name": "XUL" },
    { "_name": "Xamarin" },
    { "_name": "Xara Xtreme" },
    { "_name": "Xbox" },
    { "_name": "Xcode" },
    { "_name": "XenForo" },
    { "_name": "YUI Library" },
    { "_name": "Yahoo Developer Skills" },
    { "_name": "Yahoo! Advertising Solutions" },
    { "_name": "Yahoo! Query Language" },
    { "_name": "Yahoo! Store" },
    { "_name": "Yii" },
    { "_name": "Yola" },
    { "_name": "YouTube Development" },
    { "_name": "ZK" },
    { "_name": "Zapier" },
    { "_name": "Zen Cart" },
    { "_name": "Zend Framework" },
    { "_name": "Zend Studio" },
    { "_name": "Zendesk API Development" },
    { "_name": "Zepto" },
    { "_name": "Zoho Creator" },
    { "_name": "Zoomla" },
    { "_name": "Zope" },
    { "_name": "Zurb Foundation" },
    { "_name": "aMember" },
    { "_name": "aWeber" },
    { "_name": "accounts receivable" },
    { "_name": "agile methodologies" },
    { "_name": "bbPress" },
    { "_name": "d3.js" },
    { "_name": "dBase Administration" },
    { "_name": "dBase Programming" },
    { "_name": "data management" },
    { "_name": "docker" },
    { "_name": "e-Learning" },
    { "_name": "eBay API" },
    { "_name": "eBook Design" },
    { "_name": "ePub" },
    { "_name": "eZ Publish" },
    { "_name": "iOS Development" },
    { "_name": "iPad App Development" },
    { "_name": "iPad UI Design" },
    { "_name": "iPhone App Development" },
    { "_name": "iPhone UI Design" },
    { "_name": "iReport" },
    { "_name": "iTextSharp" },
    { "_name": "jQuery" },
    { "_name": "jQuery Mobile" },
    { "_name": "libGDX" },
    { "_name": "libcurl" },
    { "_name": "marathi language" },
    { "_name": "n2cms" },
    { "_name": "noSQL" },
    { "_name": "ooVoo Development" },
    { "_name": "openSUSE" },
    { "_name": "phpFox" },
    { "_name": "phpMyAdmin" },
    { "_name": "phpMyDirectory" },
    { "_name": "soapUI" },
    { "_name": "vtiger Adminstration" },
    { "_name": "vtiger Development" }
]